export const runtime = "nodejs";

import nodemailer from "nodemailer";
import { jsPDF } from "jspdf";

const STUDIO_EMAIL = "ifeanyihm@gmail.com";

function parseContent(content: string) {
  const lines = content.split("\n").filter((l) => l.trim());
  return lines
    .map((line) => {
      const trimmed = line.trim();
      if (trimmed.startsWith("## ") || trimmed.startsWith("# ")) {
        return {
          type: "heading" as const,
          value: trimmed.replace(/^#+\s/, ""),
        };
      } else if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
        return { type: "bullet" as const, value: trimmed.slice(2) };
      } else if (trimmed) {
        return { type: "text" as const, value: trimmed };
      }
      return null;
    })
    .filter(Boolean) as Array<{
    type: "heading" | "bullet" | "text";
    value: string;
  }>;
}

function generateBriefPDF(content: string, clientName: string): Buffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const usableW = pageW - margin * 2;
  let y = margin;

  function checkPage(needed = 10) {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  }

  // Header bar
  doc.setFillColor(28, 25, 23);
  doc.rect(0, 0, pageW, 16, "F");
  doc.setTextColor(254, 249, 195);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("KAYTEE FURNITURES", margin, 10);
  doc.setTextColor(161, 98, 7);
  doc.text("Mood Board Brief", pageW - margin, 10, { align: "right" });

  y = 28;

  doc.setTextColor(20, 20, 20);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize("Interior Design Brief", usableW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 9 + 4;

  doc.setDrawColor(161, 98, 7);
  doc.setLineWidth(0.8);
  doc.line(margin, y, margin + 40, y);
  y += 8;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(113, 113, 122);
  doc.text(`Client: ${clientName}`, margin, y);
  y += 5;
  doc.text(
    new Date().toLocaleDateString("en-GB", { dateStyle: "long" }),
    margin,
    y,
  );
  y += 10;

  for (const section of parseContent(content)) {
    if (section.type === "heading") {
      checkPage(14);
      y += 4;
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(28, 25, 23);
      doc.text(section.value.toUpperCase(), margin, y);
      y += 2;
      doc.setDrawColor(228, 228, 231);
      doc.setLineWidth(0.3);
      doc.line(margin, y, pageW - margin, y);
      y += 6;
    } else if (section.type === "bullet") {
      checkPage(8);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const lines = doc.splitTextToSize(`• ${section.value}`, usableW - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5.5 + 1;
    } else {
      checkPage(8);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(section.value, usableW);
      doc.text(lines, margin, y);
      y += lines.length * 5.5 + 3;
    }
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(248, 248, 248);
    doc.rect(0, pageH - 12, pageW, 12, "F");
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Generated by Kaytee Furnitures · Interior Design Brief",
      margin,
      pageH - 5,
    );
    doc.text(`${i} / ${totalPages}`, pageW - margin, pageH - 5, {
      align: "right",
    });
  }

  return Buffer.from(doc.output("arraybuffer"));
}

export async function POST(req: Request) {
  const { contact, lastMessage } = (await req.json()) as {
    contact: { name: string; email: string; phone: string };
    lastMessage?: string;
  };

  if (!contact?.name || !contact?.email || !contact?.phone) {
    return new Response("contact name, email and phone are required", {
      status: 400,
    });
  }

  const gmailUser = process.env.GMAIL_USER;
  const gmailPass = process.env.GMAIL_APP_PASSWORD;

  if (!gmailUser || !gmailPass) {
    return new Response("GMAIL_USER or GMAIL_APP_PASSWORD is not set", {
      status: 500,
    });
  }

  const date = new Date().toLocaleDateString("en-GB", { dateStyle: "long" });

  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: { user: gmailUser, pass: gmailPass },
    });

    // 1. Notification to Ifeanyi
    await transporter.sendMail({
      from: `"Iheme Studio Assistant" <${gmailUser}>`,
      to: STUDIO_EMAIL,
      subject: `New Project Inquiry — ${contact.name} · ${date}`,
      html: `
        <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;color:#c8cdd6;background:#08090a;border-radius:12px;overflow:hidden;">
          <div style="background:#0d0e10;border-bottom:1px solid rgba(0,212,170,0.15);padding:20px 24px;">
            <p style="margin:0;font-family:monospace;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#00d4aa;">Iheme Studio</p>
            <p style="margin:4px 0 0;font-size:11px;color:#6b7280;">New project inquiry via portfolio assistant</p>
          </div>
          <div style="padding:24px;background:#0d0e10;">
            <p style="font-size:14px;line-height:1.6;margin:0 0 20px;color:#a0a8b4;">
              Someone reached out through the portfolio assistant. Their details:
            </p>
            <table style="border-collapse:collapse;width:100%;font-size:13px;margin-bottom:20px;">
              <tr><td style="padding:7px 12px 7px 0;color:#6b7280;white-space:nowrap;">Name</td><td style="padding:7px 0;font-weight:600;color:#c8cdd6;">${contact.name}</td></tr>
              <tr><td style="padding:7px 12px 7px 0;color:#6b7280;">Email</td><td style="padding:7px 0;"><a href="mailto:${contact.email}" style="color:#00d4aa;text-decoration:none;">${contact.email}</a></td></tr>
              <tr><td style="padding:7px 12px 7px 0;color:#6b7280;">Phone</td><td style="padding:7px 0;color:#c8cdd6;">${contact.phone}</td></tr>
              <tr><td style="padding:7px 12px 7px 0;color:#6b7280;">Date</td><td style="padding:7px 0;color:#c8cdd6;">${date}</td></tr>
            </table>
            ${
              lastMessage
                ? `
            <div style="border-top:1px solid rgba(255,255,255,0.06);padding-top:16px;margin-top:4px;">
              <p style="margin:0 0 8px;font-size:11px;font-family:monospace;text-transform:uppercase;letter-spacing:0.1em;color:#6b7280;">Last assistant message</p>
              <p style="font-size:13px;line-height:1.6;color:#a0a8b4;margin:0;font-style:italic;">${lastMessage.slice(0, 300)}${lastMessage.length > 300 ? "…" : ""}</p>
            </div>`
                : ""
            }
          </div>
          <div style="padding:14px 24px;background:#08090a;border-top:1px solid rgba(255,255,255,0.04);">
            <p style="margin:0;font-size:11px;color:#4b5563;font-family:monospace;">Iheme Studio · ihemestudio.vercel.app</p>
          </div>
        </div>
      `,
    });

    // 2. Confirmation to the visitor
    await transporter.sendMail({
      from: `"Iheme Studio" <${gmailUser}>`,
      to: contact.email,
      subject: `Thanks for reaching out, ${contact.name}`,
      html: `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;color:#c8cdd6;background:#08090a;border-radius:12px;overflow:hidden;">
      <div style="background:#0d0e10;border-bottom:1px solid rgba(0,212,170,0.15);padding:20px 24px;">
        <img
          src="https://ihemestudio.vercel.app/logo.png"
          alt="Iheme Studio"
          width="180"
          height="48"
          style="display:block;width:180px;height:48px;"
        />
      </div>
      <div style="padding:28px 24px;background:#0d0e10;">
        <p style="font-size:16px;font-weight:600;margin:0 0 14px;color:#f5f4f0;">Hi ${contact.name},</p>
        <p style="font-size:14px;line-height:1.7;margin:0 0 14px;color:#a0a8b4;">
          Thanks for reaching out — your message has been received. Ifeanyi will review your inquiry and get back to you within <strong style="color:#c8cdd6;">24 hours</strong>.
        </p>
        <p style="font-size:14px;line-height:1.7;margin:0 0 24px;color:#a0a8b4;">
          In the meantime, feel free to explore the portfolio at <a href="https://ihemestudio.vercel.app" style="color:#00d4aa;text-decoration:none;">ihemestudio.vercel.app</a>.
        </p>
        <div style="background:rgba(0,212,170,0.06);border:1px solid rgba(0,212,170,0.15);border-radius:8px;padding:14px 16px;">
          <p style="margin:0;font-size:12px;color:#6b7280;">Submitted on ${date}</p>
        </div>
      </div>
      <div style="padding:14px 24px;background:#08090a;border-top:1px solid rgba(255,255,255,0.04);">
        <p style="margin:0;font-size:11px;color:#4b5563;font-family:monospace;">Iheme Studio · Lagos, Nigeria</p>
      </div>
    </div>
  `,
    });

    return new Response(JSON.stringify({ ok: true }), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("Studio contact email error:", err);
    return new Response((err as Error).message, { status: 500 });
  }
}

// export const runtime = "nodejs";

// import nodemailer from "nodemailer";
// import { jsPDF } from "jspdf";

// const KAYTEE_EMAIL = "ifeanyihm@gmail.com";

// function parseContent(content: string) {
//   const lines = content.split("\n").filter((l) => l.trim());
//   return lines
//     .map((line) => {
//       const trimmed = line.trim();
//       if (trimmed.startsWith("## ") || trimmed.startsWith("# ")) {
//         return {
//           type: "heading" as const,
//           value: trimmed.replace(/^#+\s/, ""),
//         };
//       } else if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
//         return { type: "bullet" as const, value: trimmed.slice(2) };
//       } else if (trimmed) {
//         return { type: "text" as const, value: trimmed };
//       }
//       return null;
//     })
//     .filter(Boolean) as Array<{
//     type: "heading" | "bullet" | "text";
//     value: string;
//   }>;
// }

// function generateBriefPDF(content: string, clientName: string): Buffer {
//   const doc = new jsPDF({ unit: "mm", format: "a4" });
//   const pageW = doc.internal.pageSize.getWidth();
//   const pageH = doc.internal.pageSize.getHeight();
//   const margin = 20;
//   const usableW = pageW - margin * 2;
//   let y = margin;

//   function checkPage(needed = 10) {
//     if (y + needed > pageH - margin) {
//       doc.addPage();
//       y = margin;
//     }
//   }

//   // Header bar
//   doc.setFillColor(28, 25, 23);
//   doc.rect(0, 0, pageW, 16, "F");
//   doc.setTextColor(254, 249, 195);
//   doc.setFontSize(9);
//   doc.setFont("helvetica", "bold");
//   doc.text("KAYTEE FURNITURES", margin, 10);
//   doc.setTextColor(161, 98, 7);
//   doc.text("Mood Board Brief", pageW - margin, 10, { align: "right" });

//   y = 28;

//   doc.setTextColor(20, 20, 20);
//   doc.setFontSize(20);
//   doc.setFont("helvetica", "bold");
//   const titleLines = doc.splitTextToSize("Interior Design Brief", usableW);
//   doc.text(titleLines, margin, y);
//   y += titleLines.length * 9 + 4;

//   doc.setDrawColor(161, 98, 7);
//   doc.setLineWidth(0.8);
//   doc.line(margin, y, margin + 40, y);
//   y += 8;

//   doc.setFontSize(8);
//   doc.setFont("helvetica", "normal");
//   doc.setTextColor(113, 113, 122);
//   doc.text(`Client: ${clientName}`, margin, y);
//   y += 5;
//   doc.text(
//     new Date().toLocaleDateString("en-GB", { dateStyle: "long" }),
//     margin,
//     y,
//   );
//   y += 10;

//   for (const section of parseContent(content)) {
//     if (section.type === "heading") {
//       checkPage(14);
//       y += 4;
//       doc.setFontSize(12);
//       doc.setFont("helvetica", "bold");
//       doc.setTextColor(28, 25, 23);
//       doc.text(section.value.toUpperCase(), margin, y);
//       y += 2;
//       doc.setDrawColor(228, 228, 231);
//       doc.setLineWidth(0.3);
//       doc.line(margin, y, pageW - margin, y);
//       y += 6;
//     } else if (section.type === "bullet") {
//       checkPage(8);
//       doc.setFontSize(10);
//       doc.setFont("helvetica", "normal");
//       doc.setTextColor(40, 40, 40);
//       const lines = doc.splitTextToSize(`• ${section.value}`, usableW - 4);
//       doc.text(lines, margin + 2, y);
//       y += lines.length * 5.5 + 1;
//     } else {
//       checkPage(8);
//       doc.setFontSize(10);
//       doc.setFont("helvetica", "normal");
//       doc.setTextColor(60, 60, 60);
//       const lines = doc.splitTextToSize(section.value, usableW);
//       doc.text(lines, margin, y);
//       y += lines.length * 5.5 + 3;
//     }
//   }

//   const totalPages = doc.getNumberOfPages();
//   for (let i = 1; i <= totalPages; i++) {
//     doc.setPage(i);
//     doc.setFillColor(248, 248, 248);
//     doc.rect(0, pageH - 12, pageW, 12, "F");
//     doc.setFontSize(7);
//     doc.setTextColor(160, 160, 160);
//     doc.setFont("helvetica", "normal");
//     doc.text(
//       "Generated by Kaytee Furnitures · Interior Design Brief",
//       margin,
//       pageH - 5,
//     );
//     doc.text(`${i} / ${totalPages}`, pageW - margin, pageH - 5, {
//       align: "right",
//     });
//   }

//   return Buffer.from(doc.output("arraybuffer"));
// }

// export async function POST(req: Request) {
//   const { brief, contact } = (await req.json()) as {
//     brief: string;
//     contact: { name: string; email: string; phone: string };
//   };

//   if (!brief?.trim()) return new Response("brief is required", { status: 400 });
//   if (!contact?.name || !contact?.email || !contact?.phone) {
//     return new Response("contact name, email and phone are required", {
//       status: 400,
//     });
//   }

//   const gmailUser = process.env.GMAIL_USER;
//   const gmailPass = process.env.GMAIL_APP_PASSWORD;

//   if (!gmailUser || !gmailPass) {
//     return new Response("GMAIL_USER or GMAIL_APP_PASSWORD is not set", {
//       status: 500,
//     });
//   }

//   try {
//     const pdfBuffer = generateBriefPDF(brief, contact.name);
//     const date = new Date().toLocaleDateString("en-GB", { dateStyle: "long" });

//     const transporter = nodemailer.createTransport({
//       service: "gmail",
//       auth: { user: gmailUser, pass: gmailPass },
//     });

//     // 1. Email to Kaytee team with the brief PDF
//     await transporter.sendMail({
//       from: `"Kaytee Design Assistant" <${gmailUser}>`,
//       to: KAYTEE_EMAIL,
//       subject: `New Design Brief — ${contact.name} · ${date}`,
//       html: `
//         <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;color:#1c1917;">
//           <div style="background:#1c1917;padding:20px 24px;border-radius:8px 8px 0 0;">
//             <h1 style="color:#fef9c3;margin:0;font-size:18px;">Kaytee Furnitures</h1>
//             <p style="color:#a16207;margin:4px 0 0;font-size:12px;">New Client Design Brief</p>
//           </div>
//           <div style="background:#fafaf9;border:1px solid #e7e5e4;border-top:none;padding:24px;border-radius:0 0 8px 8px;">
//             <p style="margin:0 0 16px;font-size:14px;line-height:1.6;">A new design brief has been submitted. Client details below:</p>
//             <table style="border-collapse:collapse;width:100%;font-size:13px;">
//               <tr><td style="padding:6px 12px 6px 0;color:#78716c;white-space:nowrap;">Name</td><td style="padding:6px 0;font-weight:600;">${contact.name}</td></tr>
//               <tr><td style="padding:6px 12px 6px 0;color:#78716c;">Email</td><td style="padding:6px 0;"><a href="mailto:${contact.email}" style="color:#a16207;">${contact.email}</a></td></tr>
//               <tr><td style="padding:6px 12px 6px 0;color:#78716c;">Phone</td><td style="padding:6px 0;">${contact.phone}</td></tr>
//               <tr><td style="padding:6px 12px 6px 0;color:#78716c;">Date</td><td style="padding:6px 0;">${date}</td></tr>
//             </table>
//             <p style="margin:16px 0 0;font-size:13px;color:#78716c;">The full design brief is attached as a PDF.</p>
//           </div>
//         </div>
//       `,
//       attachments: [
//         {
//           filename: `kaytee-brief-${contact.name.replace(/\s+/g, "-").toLowerCase()}.pdf`,
//           content: pdfBuffer,
//           contentType: "application/pdf",
//         },
//       ],
//     });

//     // 2. Confirmation email to the client
//     await transporter.sendMail({
//       from: `"Kaytee Furnitures" <${gmailUser}>`,
//       to: contact.email,
//       subject: `We've received your design brief, ${contact.name}!`,
//       html: `
//         <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;color:#1c1917;">
//           <div style="background:#1c1917;padding:20px 24px;border-radius:8px 8px 0 0;">
//             <h1 style="color:#fef9c3;margin:0;font-size:18px;">Kaytee Furnitures</h1>
//             <p style="color:#a16207;margin:4px 0 0;font-size:12px;">Design Brief Assistant</p>
//           </div>
//           <div style="background:#fafaf9;border:1px solid #e7e5e4;border-top:none;padding:24px;border-radius:0 0 8px 8px;">
//             <p style="font-size:15px;font-weight:600;margin:0 0 12px;">Hi ${contact.name},</p>
//             <p style="font-size:14px;line-height:1.7;margin:0 0 12px;">
//               Thank you for reaching out to Kaytee Furnitures! We've received your design brief and our team is already looking it over.
//             </p>
//             <p style="font-size:14px;line-height:1.7;margin:0 0 20px;">
//               A member of our team will be in touch with you within <strong>24 hours</strong> to discuss the next steps.
//             </p>
//             <div style="background:#fef9c3;border:1px solid #fde68a;border-radius:8px;padding:14px 16px;margin-bottom:20px;">
//               <p style="margin:0;font-size:13px;color:#78716c;">Submitted on ${date}</p>
//             </div>
//             <p style="font-size:13px;color:#78716c;margin:0;">
//               If you have any urgent questions, feel free to reply to this email.
//             </p>
//           </div>
//           <p style="text-align:center;font-size:11px;color:#a8a29e;margin-top:16px;">Kaytee Furnitures · Interior Design & Furniture</p>
//         </div>
//       `,
//     });

//     return new Response(JSON.stringify({ ok: true }), {
//       headers: { "Content-Type": "application/json" },
//     });
//   } catch (err) {
//     console.error("Email send error:", err);
//     return new Response((err as Error).message, { status: 500 });
//   }
// }
